/**
 * report.ts
 *
 * Renders a ScanResult as a Markdown report. This is deliberately the only
 * output format v1 supports - see README.md Roadmap for JSON/CSV output.
 */
import { ScanResult, Blocker, Severity } from "./scoring";

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
};

function readinessBand(score: number): string {
  if (score >= 80) return "Low migration risk - mostly documentation and validation work ahead of you.";
  if (score >= 55) return "Moderate migration risk - budget real discovery and design time before committing to a timeline.";
  if (score >= 30) return "High migration risk - this org has meaningful custom-code and data-model dependencies to work through first.";
  return "Very high migration risk - treat this as a multi-phase project, not a weekend cutover.";
}

function renderBlocker(b: Blocker, index: number): string {
  return [
    `### ${index + 1}. ${b.title}`,
    "",
    `**Severity:** ${SEVERITY_LABEL[b.severity]}`,
    "",
    b.detail,
    "",
    `**Recommendation:** ${b.recommendation}`,
    "",
  ].join("\n");
}

export function renderMarkdownReport(result: ScanResult, orgLabel: string): string {
  const lines: string[] = [];
  lines.push(`# NPSP Migration Readiness Report`);
  lines.push("");
  lines.push(`**Org:** ${orgLabel}`);
  lines.push(`**Scanned:** ${result.scannedAt}`);
  lines.push("");
  lines.push(`## Score: ${result.overallScore}/100`);
  lines.push("");
  lines.push(readinessBand(result.overallScore));
  lines.push("");
  lines.push(`**${result.blockers.length} blocker(s) found**, sorted by severity below.`);
  lines.push("");
  lines.push("## Score breakdown by check");
  lines.push("");
  lines.push("| Check | Weight | Subscore | Blockers found |");
  lines.push("|---|---|---|---|");
  for (const c of result.checks) {
    lines.push(`| ${c.checkId} | ${c.weight} | ${c.subscore}/100 | ${c.blockers.length} |`);
  }
  lines.push("");
  lines.push("## Blockers");
  lines.push("");
  if (result.blockers.length === 0) {
    lines.push("No blockers found by this scan. That does not mean the migration is zero-risk - it means this scan's specific checks didn't find anything. See README.md for what this tool does and does not check.");
  } else {
    result.blockers.forEach((b, i) => lines.push(renderBlocker(b, i)));
  }
  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by [npsp-migration-readiness-scanner](https://github.com/clear-concise-carmona/npsp-migration-readiness-scanner). " +
      "Field-level migration detail for any blocker above: [npsp-to-nonprofit-cloud-field-map](https://github.com/clear-concise-carmona/npsp-to-nonprofit-cloud-field-map)._"
  );
  return lines.join("\n");
}
